deploy:
  runs-on: ubuntu-latest
  needs: build
  environment: production

  steps:
    - name: Download Lambda Artifact
      uses: actions/download-artifact@v3
      with:
        name: lambda_function
        path: .

    - name: Upload Lambda to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "sa-east-1"
      run: |
        aws s3 cp lambda_function.zip s3://fonte-codigo-lambda-authorizer/lambda_function.zip

    - name: Trigger Terraform Pipeline
      uses: actions/github-script@v6
      with:
        script: |
          github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: 'infra-lambda-authorizer',
            workflow_id: 'ci-cd-pipeline.yml',
            ref: 'main'
          })
      env:
        GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
