name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    environment: production
    runs-on: ubuntu-latest

    steps:
      ### 1. Checkout ###
      - name: Checkout code
        uses: actions/checkout@v3

      ### 2. Setup ###
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      ### 3. Build ###
      - name: Install dependencies
        run: |
          if [ -f lambda/requirements.txt ]; then pip install -r lambda/requirements.txt; fi
      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r9 ../lambda_function.zip .
      ### 4. Deploy ###
      - name: Upload Lambda to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
        run: |
          aws s3 cp lambda_function.zip s3://fonte-codigo-lambda-authorizer/lambda_function.zip
      ### 5. Post Actions (opcional) ###
      - name: Clean up local files
        if: always()
        run: |
          rm -f lambda_function.zip
