name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  setup:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Install dependencies
        run: |
          if [ -f lambda/requirements.txt ]; then pip install -r lambda/requirements.txt; fi

      - name: Zip Lambda function
        run: |
          ls -la
          cd lambda
          zip -r9 ../lambda_function.zip

      - name: Upload Lambda to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lambda_function
          path: lambda_function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download Lambda Artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda_function
          path: .

      - name: Upload Lambda to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
        run: |
          aws s3 cp lambda_function.zip s3://fonte-codigo-lambda-authorizer/lambda_function.zip

  post_actions:
    runs-on: ubuntu-latest
    needs: deploy
    environment: production
    if: always()

    steps:
      - name: Clean up local files
        run: |
          rm -f lambda_function.zip
